Add two more test types:   compilable -- makes sure the file builds with dmd -c, but does not attempt to link or run the test   fail_compilation -- makes sure the file fails to build

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -28,9 +28,16 @@ ARGS=-inline -release -gc -O -unittest -fPIC
 runnable_tests=$(wildcard runnable/*.d)
 runnable_test_results=$(addsuffix .out,$(addprefix $(RESULTS_DIR)/,$(runnable_tests)))
 
-$(RESULTS_DIR)/%.d.out: %.d $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations $(DMD)
+compilable_tests=$(wildcard compilable/*.d)
+compilable_test_results=$(addsuffix .out,$(addprefix $(RESULTS_DIR)/,$(compilable_tests)))
+
+fail_compilation_tests=$(wildcard fail_compilation/*.d)
+fail_compilation_test_results=$(addsuffix .out,$(addprefix $(RESULTS_DIR)/,$(fail_compilation_tests)))
+
+$(RESULTS_DIR)/runnable/%.d.out: runnable/%.d $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations $(DMD)
 	$(QUIET) \
 	rm -f $@; \
+	t=$(@D)/$*; \
 	r_args=`grep REQUIRED_ARGS $<`; \
 	p_args=`grep PERMUTE_ARGS  $<`; \
 	if [ ! -z "$$r_args" ]; then r_args="$${r_args/*REQUIRED_ARGS:/}"; fi; \
@@ -38,14 +45,55 @@ $(RESULTS_DIR)/%.d.out: %.d $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations 
 	echo -e " ... $<  required: $$r_args\tpermuted args: $$p_args"; \
 	$(RESULTS_DIR)/combinations $$p_args | while read x; do \
 	    echo "dmd args: $$r_args $$x" >> $@; \
-	    $(DMD) $$r_args $$x -od$(RESULTS_DIR)/$(*D) -of$(RESULTS_DIR)/$* $<; \
+	    $(DMD) $$r_args $$x -od$(@D) -of$$t $<; \
 	    if [ $$? -ne 0 ]; then break; fi; \
-	    $(RESULTS_DIR)/$* >> $@ 2>&1 && rm $(RESULTS_DIR)/$* $(RESULTS_DIR)/$*.o; \
+	    $$t >> $@ 2>&1 && rm $$t $$t.o; \
 	    if [ $$? -ne 0 ]; then break; fi; \
 	    echo >> $@; \
        	done
 
+$(RESULTS_DIR)/compilable/%.d.out: compilable/%.d $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations $(DMD)
+	$(QUIET) \
+	rm -f $@; \
+	t=$(@D)/$*; \
+	r_args=`grep REQUIRED_ARGS $<`; \
+	p_args=`grep PERMUTE_ARGS  $<`; \
+	if [ ! -z "$$r_args" ]; then r_args="$${r_args/*REQUIRED_ARGS:/}"; fi; \
+	if [ -z "$$p_args" ]; then p_args="$(ARGS)"; else p_args="$${p_args/*PERMUTE_ARGS:/}"; fi; \
+	echo -e " ... $<  required: $$r_args\tpermuted args: $$p_args"; \
+	$(RESULTS_DIR)/combinations $$p_args | while read x; do \
+	    echo "dmd args: $$r_args $$x" >> $@; \
+	    $(DMD) -c $$r_args $$x -od$(@D) -of$$t.o $<; \
+	    if [ $$? -ne 0 ]; then break; fi; \
+	    rm -f $$t.o; \
+	    echo >> $@; \
+       	done
+
+$(RESULTS_DIR)/fail_compilation/%.d.out: fail_compilation/%.d $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations $(DMD)
+	$(QUIET) \
+	rm -f $@; \
+	t=$(@D)/$*; \
+	r_args=`grep REQUIRED_ARGS $<`; \
+	p_args=`grep PERMUTE_ARGS  $<`; \
+	if [ ! -z "$$r_args" ]; then r_args="$${r_args/*REQUIRED_ARGS:/}"; fi; \
+	if [ -z "$$p_args" ]; then p_args="$(ARGS)"; else p_args="$${p_args/*PERMUTE_ARGS:/}"; fi; \
+	echo -e " ... $<  required: $$r_args\tpermuted args: $$p_args"; \
+	$(RESULTS_DIR)/combinations $$p_args | while read x; do \
+	    echo "dmd args: $$r_args $$x" >> $@; \
+	    $(DMD) -c $$r_args $$x -od$(@D) -of$$t.o $< 2>/dev/null; \
+	    if [ $$? -eq 0 ]; then rm -f $$t.o; echo "$< should have failed to compile but succeeded instead"; /bin/false; break; fi; \
+	    echo >> $@; \
+       	done
+
 all: run_tests
+
+debug:
+	@echo "runnable_tests: $(runnable_tests)"
+	@echo "compilable_tests: $(compilable_tests)"
+	@echo "fail_compilation_tests: $(fail_compilation_tests)"
+	@echo "runnable_test_results: $(runnable_test_results)"
+	@echo "compilable_test_results: $(compilable_test_results)"
+	@echo "fail_compilation_test_results: $(fail_compilation_test_results)"
 
 clean:
 	@echo "Removing output directory: $(RESULTS_DIR)"
@@ -55,15 +103,29 @@ $(RESULTS_DIR)/.created:
 	@echo Creating output directory: $(RESULTS_DIR) 
 	$(QUIET)if [ ! -d $(RESULTS_DIR) ]; then mkdir $(RESULTS_DIR); fi
 	$(QUIET)if [ ! -d $(RESULTS_DIR)/runnable ]; then mkdir $(RESULTS_DIR)/runnable; fi
+	$(QUIET)if [ ! -d $(RESULTS_DIR)/compilable ]; then mkdir $(RESULTS_DIR)/compilable; fi
+	$(QUIET)if [ ! -d $(RESULTS_DIR)/fail_compilation ]; then mkdir $(RESULTS_DIR)/fail_compilation; fi
 	$(QUIET)touch $(RESULTS_DIR)/.created
 
-run_tests: start_runnable_tests
+run_tests: start_runnable_tests start_compilable_tests start_fail_compilation_tests
 
 run_runnable_tests: $(runnable_test_results)
 
 start_runnable_tests: $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations
 	@echo "Running runnable tests"
 	$(QUIET)$(MAKE) --no-print-directory run_runnable_tests
+
+run_compilable_tests: $(compilable_test_results)
+
+start_compilable_tests: $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations
+	@echo "Running compilable tests"
+	$(QUIET)$(MAKE) --no-print-directory run_compilable_tests
+
+run_fail_compilation_tests: $(fail_compilation_test_results)
+
+start_fail_compilation_tests: $(RESULTS_DIR)/.created $(RESULTS_DIR)/combinations
+	@echo "Running fail compilation tests"
+	$(QUIET)$(MAKE) --no-print-directory run_fail_compilation_tests
 
 $(RESULTS_DIR)/combinations: combinations.d $(RESULTS_DIR)/.created
 	@echo "Building combinations tool"
