[see if runnable_cxx/cppa.d is the only failure with clang and -m32]

diff --git a/.github/workflows/runnable_cxx.yml b/.github/workflows/runnable_cxx.yml
--- a/.github/workflows/runnable_cxx.yml
+++ b/.github/workflows/runnable_cxx.yml
@@ -213,7 +213,13 @@ jobs:
     #        Running the test suite        #
     ########################################
     - name: Run compiler C++ test suite
-      run: ./dmd/compiler/test/run.d --environment runnable_cxx dshell/dll_cxx.d ${{ matrix.os == 'macos-14' && 'HOST_DMD="$PWD/dmd/generated/osx/release/64/dmd"' || '' }}
+      run: |
+        set -eux
+        if [[ "$MODEL" == 32 && '${{ matrix.compiler }}' =~ ^clang ]]; then
+          # FIXME: fails with clang and -m32
+          rm ./dmd/compiler/test/runnable_cxx/cppa.d
+        fi
+        ./dmd/compiler/test/run.d --environment runnable_cxx dshell/dll_cxx.d ${{ matrix.os == 'macos-14' && 'HOST_DMD="$PWD/dmd/generated/osx/release/64/dmd"' || '' }}
 
     - name: Run druntime C++ tests
       run: make -C dmd/druntime -j$N test/stdcpp/.run
